# gen-fake-game.ps1 - generate a synthetic "saturated game-dev folder" for testing
# PopBot's Perforce + VHDX very-large-project support.
#
# Produces a tree that LOOKS like a real (Unreal/Unity-ish) game project:
#   - Source/ + Plugins/*/Source : many small code files (.cpp/.h/.cs)
#   - Content/ + Plugins/*/Content : large pseudo-random binary "assets"
#       (.uasset/.umap/.uexp), the bulk of the bytes
#   - Config/ : .ini files
#   - DERIVED/WARM dirs (Binaries, Intermediate, Saved, DerivedDataCache, Library):
#       the "saturated" build/cache state that makes a slot warm. p4-ignored.
#   - .p4ignore + a .uproject marker at the root
#
# Source/assets are what you submit to Perforce; the derived dirs simulate the
# warm state generated by a build (the thing the frozen VHDX base captures).
#
# Usage:
#   pwsh scripts/gen-fake-game.ps1 -Root C:\fakegame -TotalSizeGB 2
#   pwsh scripts/gen-fake-game.ps1 -Root C:\fakegame -TotalSizeGB 0.1 -Seed 7   # quick smoke

[CmdletBinding()]
param(
  [Parameter(Mandatory)] [string] $Root,
  [double] $TotalSizeGB = 2.0,     # total tree size target (assets dominate)
  [int]    $Seed        = 1,
  [int]    $SourceFiles = 400,     # number of small code files
  [double] $WarmFraction = 0.35,   # share of asset bytes also mirrored into derived dirs
  [switch] $Clean                  # wipe Root first
)

$ErrorActionPreference = 'Stop'
$rng = [Random]::new($Seed)

function New-RandomFile {
  param([string]$Path, [long]$Bytes)
  $dir = Split-Path $Path -Parent
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  $chunk = 1MB
  $buf = [byte[]]::new($chunk)
  $fs = [IO.File]::Create($Path)
  try {
    [long]$left = $Bytes
    while ($left -gt 0) {
      $n = [Math]::Min($chunk, $left)
      $rng.NextBytes($buf)
      $fs.Write($buf, 0, [int]$n)
      $left -= $n
    }
  } finally { $fs.Dispose() }
}

function New-CodeFile {
  param([string]$Path, [string]$Sym)
  $dir = Split-Path $Path -Parent
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
  $lines = 60 + $rng.Next(240)
  $sb = [Text.StringBuilder]::new()
  [void]$sb.AppendLine("// AUTO-GENERATED synthetic source - $Sym")
  [void]$sb.AppendLine("#pragma once")
  [void]$sb.AppendLine("namespace FakeGame {")
  [void]$sb.AppendLine("class $Sym {")
  for ($i=0; $i -lt $lines; $i++) {
    [void]$sb.AppendLine("  void Method$i() { int x = $($rng.Next(99999)); for (int i=0;i<x;i++) {} }")
  }
  [void]$sb.AppendLine("};")
  [void]$sb.AppendLine("}")
  [IO.File]::WriteAllText($Path, $sb.ToString())
}

# ---- prep ----
if ($Clean -and (Test-Path $Root)) { Remove-Item $Root -Recurse -Force }
New-Item -ItemType Directory -Path $Root -Force | Out-Null
$totalBytes = [long]($TotalSizeGB * 1GB)

Write-Host "Generating ~$TotalSizeGB GB synthetic game project at $Root (seed=$Seed)"

# ---- root markers ----
@"
{ "FileVersion": 3, "EngineAssociation": "5.4", "Category": "", "Description": "FakeGame" }
"@ | Set-Content "$Root\FakeGame.uproject"

@"
# Derived/build output - not under version control
Binaries/
Intermediate/
Saved/
DerivedDataCache/
Library/
*.tmp
"@ | Set-Content "$Root\.p4ignore"

New-Item -ItemType Directory -Path "$Root\Config" | Out-Null
"[/Script/Engine.Engine]`r`nbSmoothFrameRate=True" | Set-Content "$Root\Config\DefaultEngine.ini"

# ---- source code (small, many files) ----
Write-Host "  source: $SourceFiles code files"
$modules = @('Core','Gameplay','UI','Net','AI','Render','Audio')
for ($i=0; $i -lt $SourceFiles; $i++) {
  $m = $modules[$rng.Next($modules.Count)]
  $ext = @('.cpp','.h','.cs')[$rng.Next(3)]
  New-CodeFile -Path "$Root\Source\$m\Class$i$ext" -Sym "Class$i"
}

# ---- assets (big binaries, the bulk of bytes) ----
# Reserve ~12% for source/config/misc already written; assets get the rest.
$assetBudget = [long]($totalBytes * 0.88)
$assetExts = @('.uasset','.umap','.uexp','.ubulk')
$assetDirs = @('Content\Characters','Content\Environments','Content\Audio',
               'Content\VFX','Content\Maps','Plugins\Mega\Content')
Write-Host ("  assets: filling ~{0:N1} GB of binaries" -f ($assetBudget/1GB))
[long]$written = 0
$assetPaths = New-Object System.Collections.Generic.List[string]
$idx = 0
while ($written -lt $assetBudget) {
  $d = $assetDirs[$rng.Next($assetDirs.Count)]
  $e = $assetExts[$rng.Next($assetExts.Count)]
  # asset sizes 2-40 MB, clamped to remaining budget
  $sz = [long]((2 + $rng.Next(38)) * 1MB)
  if ($sz -gt ($assetBudget - $written)) { $sz = $assetBudget - $written }
  if ($sz -le 0) { break }
  $p = "$Root\$d\Asset$idx$e"
  New-RandomFile -Path $p -Bytes $sz
  $assetPaths.Add($p)
  $written += $sz; $idx++
}

# ---- derived/warm state (simulates a built project; p4-ignored) ----
# Mirror a fraction of asset bytes into cache dirs so the "saturated" tree is
# realistically larger than the submitted source - this is what the VHDX base
# freezes and every warm slot inherits.
$warmBudget = [long]($written * $WarmFraction)
Write-Host ("  warm/derived: ~{0:N1} GB of cache/intermediate" -f ($warmBudget/1GB))
$warmDirs = @('DerivedDataCache','Intermediate\Build','Binaries\Win64','Saved\Shaders','Library\ShaderCache')
[long]$w = 0; $widx = 0
while ($w -lt $warmBudget) {
  $d = $warmDirs[$rng.Next($warmDirs.Count)]
  $sz = [long]((1 + $rng.Next(20)) * 1MB)
  if ($sz -gt ($warmBudget - $w)) { $sz = $warmBudget - $w }
  if ($sz -le 0) { break }
  New-RandomFile -Path "$Root\$d\cache$widx.ddc" -Bytes $sz
  $w += $sz; $widx++
}

# ---- report ----
$allFiles = Get-ChildItem $Root -Recurse -File
$sum = ($allFiles | Measure-Object Length -Sum).Sum
$srcCount  = (Get-ChildItem "$Root\Source" -Recurse -File -ErrorAction SilentlyContinue).Count
Write-Host ""
Write-Host ("DONE  total={0:N2} GB  files={1:N0}  source={2}  assets={3}  warmFiles={4}" -f `
  ($sum/1GB), $allFiles.Count, $srcCount, $assetPaths.Count, $widx)
Write-Host "Submit to Perforce: everything EXCEPT the dirs listed in $Root\.p4ignore"